name: Run Application and Lint

on:
  push:
    branches:
      - master
      # Add additional branches if needed

jobs:
  run-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start Application
        run: node app.js
        # Replace "server.js" with the appropriate file to start your application

      - name: Run ESLint
        run: npx eslint .
