name: Build and Lint

on:
  push:
    branches:
      - main
      # Add additional branches if needed

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        # Replace "npm run build" with the command to start your application

      - name: Run ESLint
        run: npx eslint .
